<?php

/**
 * @file
 * Bean Admin UI
 */

/**
 * Implements hook_menu().
 */
function bean_admin_ui_menu() {
  $items = array();

  $items['admin/structure/block/types'] = array(
    'title' => 'Block Types',
    'description' => 'Manage Block Types',
    'page callback' => 'bean_admin_ui_admin_page',
    'access arguments' => array('administer block types'),
    'file' => 'bean_admin_ui.admin.inc',
  );

  $items['admin/structure/block/types/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/structure/block/types/add'] = array(
    'title' => 'Add block type',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bean_admin_ui_type_form'),
    'access arguments' => array('administer block types'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'bean_admin_ui.admin.inc',
  );

  $items['admin/structure/block/types/manage/%bean_type'] = array(
    'title' => 'Edit block type',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bean_admin_ui_type_form', 5),
    'access arguments' => array('administer block types'),
    'file' => 'bean_admin_ui.admin.inc',
  );
  $items['admin/structure/block/types/manage/%bean_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/structure/block/types/manage/%bean_type/delete'] = array(
    'title' => 'Delete',
    'page arguments' => array('bean_admin_ui_type_delete_confirm', 5),
    'access arguments' => array('administer block types'),
    'file' => 'bean_admin_ui.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory()
 */
function bean_admin_ui_ctools_plugin_directory($module, $type) {
  if ($module == 'bean') {
    return 'plugins';
  }
}

/**
 * Implements hook_bean_types_api_info().
 */
function bean_admin_ui_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types()
 */
function bean_admin_ui_bean_types() {
  $plugins = array();


  // Add in the types defined in the UI
  $bean_types = bean_admin_ui_get_types();

  foreach ($bean_types as $bean_type) {
    $plugins[$bean_type->type] = array(
      'label' => $bean_type->label,
      'type' => $bean_type->type,
    );

    $plugins[$bean_type->type] += _bean_admin_default_plugin();
  }

  return $plugins;
}

/**
 * Get The Bean Types
 */
function bean_admin_ui_get_types() {
  $bean_types = &drupal_static(__FUNCTION__);

  if (empty($bean_types)) {
    $cache = cache_get('bean_types');
    if (empty($cache->data)) {
      $bean_types = db_query('SELECT * FROM {bean_type}')->fetchAllAssoc('type');
      cache_set('bean_types', $bean_types);
    }
    else {
      $bean_types = $cache->data;
    }
  }

  return $bean_types;
}

/**
 * The Default plugin settings
 */
function _bean_admin_default_plugin() {
  return array(
    'label' => '',
    'type' => '',
    'editable' => TRUE,
    'handler' => array(
      'path' => drupal_get_path('module', 'bean_admin_ui') . '/plugins',
      'file' => 'custom.inc',
      'class' => 'bean_custom',
      'parent' => 'bean',
    ),
  );
}