<?php

/**
 * Implements hook_bean_types().
 */
function bean_all_bean_types() {
  $plugins = array();

  $default = array(
    'file' => 'all.inc',
    'path' => drupal_get_path('module', 'bean_all') . '/plugins',
    'handler' => array(
      'class' => 'BeanAll',
      'parent' => 'bean',
    ),
  );

  foreach (module_implements('block_info') as $module) {
    if ($module !== 'bean') {
      $module_blocks = module_invoke($module, 'block_info');
      if (!empty($module_blocks)) {
        foreach ($module_blocks as $delta => $block) {
          $block = (object) $block;
          $block->module = $module;
          $block->delta = $delta;
          $plugins["$module-$delta"] = array(
            'label' => $block->info,
            'description' => $block->info,
            'name' => "$module-$delta",
            'block' => $block
          ) + $default;
        }
      }
    }
  }

  return $plugins;
}

/**
 * Implements hook_bean_types_api_info().
 */
function bean_all_bean_types_api_info() {
  return array(
    'api' => 4,
  );
}
